# Generated by Django 4.2.3 on 2023-07-15 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proyect',
            new_name='Project',
        ),
    ]
